version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node

      - image: psql 13.2
        environment:
          POSTGRES_USER: 'kn'
          port: 5432
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: whether_sweater
          command: bundle -v
      - ruby/bundle-install

      - checkout
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run: sudo apt install -y postgresql-client || true
      - run:
          name: Database Setup
          command:
            bundle exec rake db:create
            bundle exec rake db:structure:load
      - run: mkdir ~/rspec
      - run:
          command: bundle exec rspec
          when: always
      - store_test_results:
          path: ~/rspec